### ISSUE TITLE
Please add groups.addLeader and groups.removeLeader api calls

### ISSUE THREAD

**Issue by jsalatiel** [jadolg/rocketchat_API#110]
Would it be possible to add the following api calls?

https://docs.rocket.chat/api/rest-api/methods/groups/addleader
https://docs.rocket.chat/api/rest-api/methods/groups/removeleader

**Comment by sctEdwin** [comment]
@jsalatiel 
You can make yourself the wrapper function for addleader and removeleader inside the script groups.py.
(You can refer to how the other functions are wrote, they look quite similar)
https://github.com/jadolg/rocketchat_API/blob/master/rocketchat_API/APISections/groups.py

Once you have those functions added, you can use those functions right away.
(Since "RocketChat" class already contains "RocketChatGroups" class as described in rocketchat.py, you do not need to add anything to "rocketchat.py" in this case)

**Comment by jadolg** [comment]
Version [1.13.0](https://pypi.org/project/rocketchat-API/) is published with these changes :smile:
