### ISSUE TITLE
Adding User To Groups Suddenly Broken

### ISSUE THREAD

**Issue by redpillquants** [jadolg/rocketchat_API#127]
I've been using rocketchat_API very successfully for the past year. The way I manage users is done via an admin python script that has worked flawlessly thus far. 

Most recently I realized that creating a new user via my admin script did not result in that user being added to the necessary groups. This is the call being made:

api.groups_invite('group_name', userid).json()

I have not made any code changes so my assumption is that the new version of RocketChat broke this? I just updated rocketchat_API, so I'm definitely on the latest build.

Can you please test this on your end and let me know if you are able to still make this call successfully?

Thanks in advance.

Michael

**Comment by redpillquants** [comment]
We've dug a big deeper and the problem seems to stem from the following:

When users are added to a channel, they have to be added by the userid which is hashed. The channels are also hashed and similarly the channel ID hash has to be found to add someone to a channel. The channel ID hash search method is working fine... however NOT the method for finding the hashed userid.

Our script has a method that fetches a list of all users from RC then parses through the list to find a match by e-mail address. When it finds a match, it returns the hashed userid.

The problem is the fetch user list method is only returning a partial list of users. Since this worked just fine before we are pretty sure if a bug in either RC or some incompatibility between the latest version of rocketchat_API and the new stand-alone server. We did update the rocketchat_API lib to the very latest but it didn't change anything.

**Comment by JayBraker** [comment]
So if I got this right, you have a custom script that creates a new user, then searches for the group-id and finally searches for the user-id of the user it just created?
Keep in mind this is just a wrapper for (almost) all of RocketChats official endpoints.

You have to conform to the specified parameters: To invite a user to a group, you have to specify the room-id and the user-id.
(https://developer.rocket.chat/api/rest-api/methods/groups/invite)

Upon successfully creating a new user, your response will contain the user data as json, it contains the user-id you're looking for.
(https://developer.rocket.chat/api/rest-api/methods/users/create)

The endpoint for listing all users should returns every user on the server, the level of detail depends on your permissions:
In order to get the users email, the caller has own admin priviledges
(https://developer.rocket.chat/api/rest-api/methods/users/list)

> The problem is the fetch user list method is only returning a partial list of users. 

Partial as in some details were missing or not all users were listed?
It has not occured to me that users were not listed by /users/list
In case of the former, refer to the Rocket.Chat documentation for /users/list and check your permissions

**Comment by redpillquants** [comment]
Right - I think we are in sync on the general steps involved. And again, this has worked just fine for over a year now.

When I said partial I meant that it's returning users but not ALL of them. FYI - the bot that's doing the query has admin permissions. There's no reason it should only be able to pull a partial list of all users in the system.

**Comment by redpillquants** [comment]
Any more insights that would help?

**Comment by JayBraker** [comment]
Have you tried calling the API Endpoint for List Users via alternative method (i.e. cURL) to verify the error is with this wrapper?
Sorry haven't gotten around to recreate yet

**Comment by redpillquants** [comment]
Understood - I hired a top RC contributor and he narrowed it down to this:

https://github.com/RocketChat/Rocket.Chat/pull/21469

If we figure out a fix I will let you know.

**Comment by jadolg** [comment]
Oh, it seems you might be hitting a pagination problem.
users.list is paginated. This means it will only return a partial list of users every time.
We are still not handling pagination in a beautiful way in the wrapper, but you can use this information to get the whole list https://developer.rocket.chat/api/rest-api/offset-and-count-and-sort-info

**Comment by mmehrle** [comment]
I found the solution actually. It was the REST API setting in the admin section of RC which is limited to 50 by default. I assume that is what you are referring to, Jadolg?

Anyway, I set it to 1000000 now and it's working again.

**Comment by jadolg** [comment]
> I found the solution actually. It was the REST API setting in the admin section of RC which is limited to 50 by default. I assume that is what you are referring to, Jadolg?
> 
> Anyway, I set it to 1000000 now and it's working again.

Well, yes and no :smile: 
Doing it like this solves the problem but your script is not generic enough to work on other servers.
Using the API pagination would be a better solution.
Anyway, if it works for you then that's great :smile: 
I'll close the issue.

**Comment by redpillquants** [comment]
Understood and I appreciate your pointer, Jadolg. I don't run this script anywhere else so this fix should suffice.
