### ISSUE TITLE
Implement livechat methods

### ISSUE THREAD

**Issue by jadolg** [jadolg/rocketchat_API#47]
https://rocket.chat/docs/developer-guides/rest-api/livechat/

**Comment by dudanogueira** [comment]
Hi @jadolg !

Great work! Thanks!

I started playing around with the Livechat API support:
https://github.com/dudanogueira/rocketchat_API/tree/livechat

Let me know if I am on the right track, and if I can contribute with your work!

**Comment by jadolg** [comment]
That's fantastic @dudanogueira !
Please feel free to contribute as much as you want.
Just make sure the new code is tested and passing the travis/codacy steps and I'll merge your pull requests as soon as they hit my inbox :)

**Comment by dudanogueira** [comment]
Hi @jadolg Can you point me how to properly run the tests locally?

Is there way to run the test multiple times? Otherwise I run into problems

I tried with
`python -m unittest discover tests/
`
but I ran into this problem:

FFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_channels_add_all (tests.TestChannels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dudanogueira/dev/labs/rocketchat_API/tests/tests.py", line 307, in setUp
    self.fail("can't create test user")
AssertionError: can't create test user
...

I will try to push the code to a branch to see if the travis/codacy (never used this) will trigger.

Thanks!

**Comment by jadolg** [comment]
Hi @dudanogueira 
First you need to start a rocket.chat server. The version tests are using right now is **0.73.1** but I'm working on fixing the code already to be able to test with **2.1.0**. I always use **Docker** and **docker-compose** to start the rocket.chat server.
When the server is running I use **pytest** to execute the tests.
Make sure you have installed **pytest-cov pytest-flakes pytest-pep8** and run `pytest tests rocketchat_API -x --cov=./ --pep8 --flakes` to execute all the tests.

**Comment by jadolg** [comment]
@dudanogueira since it was so difficult to integrate these changes with the new versions of the library I decided to go ahead and move the development to another PR. I'm working on it in https://github.com/jadolg/rocketchat_API/pull/116
Please have a look and tell me if anything looks wrong.
