### ISSUE TITLE
Match error: Unknown key in field pass

### ISSUE THREAD

**Issue by scream4ik** [jadolg/rocketchat_API#8]
When i try to create new user i get error: {'error': 'Match error: Unknown key in field pass', 'success': False}

Are you sure that  "pass" is needed in dict reduced_args in __call_api_post method?

**Comment by jadolg** [comment]
What version of Rocket.Chat are you using? Version 0.58 checks that you don't use **pass** on users.create. Turns out that there is a difference on the methods that use the password since some use *password* and some *pass* . Since **pass** is a reserved word in Python I had to inject it on the post requests every time you use the **password** param so POST works for all methods. I've done some work around it, but not pushed a new version just yet, so the code on github should be OK but not the one on PyPi

**Comment by jadolg** [comment]
Just pushed to Pypi [version 0.6.2](https://pypi.python.org/pypi/rocketchat-API/0.6.2)
Please let me know if it works for you.

**Comment by scream4ik** [comment]
Many thanks. Now all fine

**Comment by RashmiGulati** [comment]
Hi @jadolg 
I get a error when creating a user , when i print reduced_args in __call_api_post method i get correct credentials through which i can create manual account on my server 
following is the error:
RocketAuthenticationException at /api/v1/chat/token/
No exception message supplied
its because user is not registered thats what i am sure of , can you help in this

**Comment by Sourabhah** [comment]
Hi @jadolg
I get a error when creating a user , when i print reduced_args in __call_api_post method i get correct credentials through which i can create manual account on my server
following is the error:
RocketAuthenticationException at /api/v1/chat/token/
No exception message supplied
its because user is not registered thats what i am sure of , can you help in this

**Comment by jadolg** [comment]
Hi @Sourabhah 
what version of Rocket.Chat are you using and what version of the library?

**Comment by leolage** [comment]
Ola, descobri o problema, falta fechar uma chave na documentacao original do site! Segue o codigo corrigido, por favor corrijam la na documentação oficial. Obrigado Daniel e Zac por me ajudarem nisto.

curl -X POST \
-H "Content-type:application/json" \
https://chat.hostone.com.br/api/v1/livechat/visitor -d '{"visitor":{"name":"Leonardo","email":"visitor@rocket.chat","token":"djh38jsd993","phone":"55 5155555555","customFields":[{"key":"address","value":"Rocket.Chat street","overwrite":true}]}}'

**Comment by leolage** [comment]
Ola, descobri o problema, falta fechar uma chave na documentacao original do site! Segue o codigo corrigido, por favor corrijam la na documentação oficial. Obrigado Daniel e Zac por me ajudarem nisto.

curl -X POST
-H "Content-type:application/json"
http://localhost:3000/api/v1/livechat/visitor -d '{"visitor":{"name":"Leonardo","email":"visitor@rocket.chat","token":"djh38jsd993","phone":"55 5155555555","customFields":[{"key":"address","value":"Rocket.Chat street","overwrite":true}]}}'
